### ISSUE TITLE
这都能中

### ISSUE THREAD

**Issue by rubbish001** [KuanchihHuang/PTT#1]

**Comment by weijielyu** [comment]
能拜读一下你的paper吗？

**Comment by KuanchihHuang** [comment]
Thanks for you criticism, It's always welcomed to bring up new improvements. Please provide more specific suggestions. Thanks.

**Comment by rubbish001** [comment]
> Referen
BEVFixV1,BEVFixV2,2个版本的V1，在Transfusion-L基础上提升2.5mAP（test），V2在focalFormer基础上提升0.5mAP（val）

**Comment by rubbish001** [comment]
> 能有幸拜读一下你的paper吗？

BEVFixV1,BEVFixV2,2个版本的V1，在Transfusion-L基础上提升2.5mAP（test），V2在focalFormer基础上提升0.5mAP（val）
