### ISSUE TITLE
The actual operation process of PTT model

### ISSUE THREAD

**Issue by luoxiaoliaolan** [KuanchihHuang/PTT#2]
Thank you for your outstanding work. When will the code be open sourced? I would like to know the actual operation process of the PTT model. Can the end-to-end operation process be achieved? Or does it need to be done step by step?

**Comment by KuanchihHuang** [comment]
Hi, thanks for your interest in our work. Our approach is a two-stage framework that uses CenterPoint as the region proposal network to generate each frame 3D box, similar to MSF (CVPR'23) and MPPNet (ECCV'22). 

We will release the code soon.

**Comment by KuanchihHuang** [comment]
Thanks for your patience. We have released our code.

**Comment by luoxiaoliaolan** [comment]
Think you very much! I will learn this code for new 3d object detection.
