### ISSUE TITLE
Hello! I'm very interedted in your work.However,there's something confusing me. Would you explain the meaning and values of Future-Aware Activation since it is generated based current proposals.Is is necessary of theory?

### ISSUE THREAD

**Issue by MSunDYY** [KuanchihHuang/PTT#3]

**Comment by KuanchihHuang** [comment]
Hi, thanks for your interest in our work. 
Inspired by the anticipation of future action in the action recognition field [onlineaction2019iccv], we observe that predicting future information is also important for 3D estimation in the current frame by improving feature learning. 

[onlineaction2019iccv] Temporal Recurrent Networks for Online Action Detection, ICCV'19

**Comment by MSunDYY** [comment]
Thanks for your reply! I've read the paper and observed that the owner used the ground truth label in future frames to train while you don't.Did you consider add extra supervision to aid training?

**Comment by MSunDYY** [comment]
Thanks for your reply! I've read the paper and observed that the owner used the ground truth label in future frames to train while you don't.Did you consider adding extra supervisions to aid training?

**Comment by KuanchihHuang** [comment]
Yes, we do this. I will add more details when releasing the code.

**Comment by MSunDYY** [comment]
All right.Looking forward to your release!

**Comment by KuanchihHuang** [comment]
Thanks for your patience. We have released our code.
