### ISSUE TITLE
about parallel

### ISSUE THREAD

**Issue by MSunDYY** [KuanchihHuang/PTT#5]
Hello,I have a question.When acquiring box trajectories,in mppnet,parallelization is not allowed! Would you solve it ?Or how did you generate accurate box trajectories? It's very costly to cycle 64 times to generate 64 box trajectories,

**Comment by KuanchihHuang** [comment]
Hi, thanks for your interest in our work. 
We follow MPPNet to link the box trajectories. Yes, we found that setting USE_TRAJ_AUG to True would take a lot of time.

**Comment by MSunDYY** [comment]
Hello, I'm sorry that I can't reproduce your result as shown in your paper.I have observed that in the logging text you give the recall rate of ROIs in the first stage is much higher than mine.So can you give me the results.pkl file or tell me how do you generate the Proposals?Looking forward to your reply!&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KuanchihHuang/PTT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月19日(星期三) 上午8:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KuanchihHuang/PTT] about parallel (Issue #5)





 
Hi, thanks for your interest in our work.
 We follow MPPNet to link the box trajectories. Yes, we found that setting USE_TRAJ_AUG to True would take a lot of time.

**Comment by MSunDYY** [comment]
Hello,sorry to bother you that would you tell me that how do you train your RPN network or give me your result.pkl file,which is very important to me.Looking forward to your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KuanchihHuang/PTT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月19日(星期三) 上午8:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KuanchihHuang/PTT] about parallel (Issue #5)





 
Hi, thanks for your interest in our work.
 We follow MPPNet to link the box trajectories. Yes, we found that setting USE_TRAJ_AUG to True would take a lot of time.
